
server:
  port: 8084

camel:
  springboot:
    name: 'rest-service'


spring:
  application:
    name: rest-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: true
  datasource:
#    url: ${DB_SERVER:jdbc:postgresql://localhost:5432/cataloguedb?useTimezone=true&serverTimezone=Africa/Lagos}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:root}
#    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

route:
  book:
    findAllBooks: direct:findAllBooks
    findBookById: direct:findBookById
    findBookByTitle: direct:findBookByTitle
    findBookByAuthor: direct:findBookByAuthor
    findBookByIsbn: direct:findBookByIsbn
    saveBook: direct:saveBook
    removeBook: direct:removeBook

  movie:
    findAllMovies: direct:findAllMovies