
server:
  port: 8080

camel:
  springboot:
    name: 'rest-service'


spring:
  application:
    name: rest-service
#  jpa:
#    hibernate.ddl-auto: update
#    properties:
#      hibernate.temp.use_jdbc_metadata_defaults: true
#  datasource:
#    url: ${DB_SERVER:jdbc:postgresql://localhost:5432/camel3db?useTimezone=true&serverTimezone=Africa/Lagos}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:root}
#    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

route:
  book:
    findAllBooks: direct:findAllBooks
    findBookByName: direct:findBookByName
    removeBook: direct:removeBook
    saveBook: direct:saveBook

  movie:
    findAllMovies: direct:findAllMovies